try {
    console.log(1)
    setTimeout(() => {
     console.log(2)   
    });
} catch (error) {
    
}finally{
    console.log(3)
}